var express = require('express');
var router = express.Router();
var passport = require('passport');
var SessionData = require('../models/session');
router.get('/SessionForm',SessionData.getAllSession);
router.post("/SessionForm", SessionData.addSession);
router.get("/SessionForm", SessionData.getAllSession);
router.get("/SessionForm/delete/:id", SessionData.deleteSession);
router.put("/SessionForm/:id", SessionData.UpdateSession);
router.get("/SessionForm/:id", SessionData.getSessionById);
module.exports = router;